### ISSUE TITLE
  core/variant/variant_utility.cpp:1091 - #Undefined type Post Processing addon - verify it has been properly integrated.

### ISSUE THREAD

**Issue by Firezac** [ItsKorin/Godot-Post-Process-Plugin#6]
**Describe the bug**
Every time I set any of the filters, this error appears on the terminal. Also, it applies the filters but I am not able to modify its attributes, so they are stuck on the initial value.

**Comment by KorinDev** [comment]
sorry for the long wait, il fix the bugs as soon as possible

**Comment by Firezac** [comment]
No problem, thanks for your return. Can't wait for the fix! :)

**Comment by SAED2906** [comment]
I fixed it, waiting for review on PR

**Comment by KorinDev** [comment]
Thank's @SAED2906 for fixing the bug!

**Comment by FlashlightET** [comment]
![image](https://github.com/ItsKorin/Godot-Post-Process-Plugin/assets/29938499/d17021f1-86d7-4027-8587-daa99a90759e)
still getting this error

**Comment by Sp1cyP3pp3r** [comment]
![image](https://github.com/ItsKorin/Godot-Post-Process-Plugin/assets/83341703/74fc968b-5dd4-4ab2-af85-65342d4c2812)

Still getting it too

**Comment by Sp1cyP3pp3r** [comment]
_fixed_ by replacing the PostProcess node with a new one?

**Comment by KorinDev** [comment]
Sorry didnt notice this, are you using the new updated version? (i updated 0.1.0 twice, the newer version should have the issue fixed)
Otherwise reloading the **scene** works aswell

(my mail is cluttered with random emails and github did not show the notifications as the issue was marked as closed)

**Comment by Sp1cyP3pp3r** [comment]
> Sorry didnt notice this, are you using the new updated version?

I downloaded this plugin today from the AssetLibrary in Godot, it says 0.1.0. And I'm quite fascinated with what it can do, you're doing great job.

> Otherwise reloading the scene works aswell

Yes, it helps too, but it seems only temporarily. The issue seems to (re)occur sporadically after running the project (F5) and closing it, returning to work in the editor.

**Comment by MartinFretigne** [comment]
I too have this error (using Godot 4.3.rc1 and Post Processing addon 0.1.0 downloaded from the asset library). The error is spammed continuously.
```
ERROR: #Undefined type Post Processing addon - verify it has been properly integrated.
   at: push_error (core/variant/variant_utility.cpp:1092)
```
 @ItsKorin
